---
name: flu_proj
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  retrofit: ^4.0.1
  analyzer: ^5.7.1
  dio: ^5.0.2
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1
  json_annotation: ^4.8.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.0.20
  freezed: ^2.3.2
  get_it: ^7.2.0
  lottie: ^2.3.1
  country_code_picker: ^3.0.0
  image_picker: ^0.8.7+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/json/
  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Bold.ttf
      weight: 700
    - asset: assets/fonts/Montserrat-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Montserrat-Light.ttf
      weight: 300
    - asset: assets/fonts/Montserrat-Medium.ttf
      weight: 500
    - asset: assets/fonts/Montserrat-Regular.ttf
      weight: 400
